# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFM1app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activmad',
            name='descricion',
        ),
        migrations.AddField(
            model_name='activmad',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
