# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFM1app', '0002_auto_20160613_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activbcn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('idevento', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('fechaevento', models.DateTimeField()),
                ('fechafin', models.DateTimeField()),
            ],
        ),
    ]
